import { Subject } from "./types";
import { randomUUID } from "crypto";
import { DEFAULT_RESEARCHERS } from "./default-researchers";

function s(text: string, category: string): Subject {
  return { id: randomUUID(), text, category };
}

const SLEEP_TOPICS: Subject[] = [
  // Sleep Science
  s("How magnesium glycinate improves deep sleep", "Sleep Science"),
  s("What is sleep architecture and why it matters", "Sleep Science"),
  s("REM sleep: why it's critical for memory and mood", "Sleep Science"),
  s("Slow-wave sleep: the stage that repairs your body", "Sleep Science"),
  s("How L-theanine creates alpha brain waves", "Sleep Science"),
  s("Apigenin: the chamomile compound that helps you sleep", "Sleep Science"),
  s("Why magnesium deficiency causes insomnia", "Sleep Science"),
  s("How cortisol disrupts sleep architecture", "Sleep Science"),
  s("The role of adenosine in building sleep pressure", "Sleep Science"),
  s("Melatonin vs. magnesium: what's the difference", "Sleep Science"),
  s("How GABA helps your brain wind down at night", "Sleep Science"),
  s("The science of sleep cycles (why 90 minutes matters)", "Sleep Science"),
  s("Why your body temperature drops during sleep", "Sleep Science"),
  s("How deep sleep clears amyloid plaques from the brain", "Sleep Science"),
  s("The connection between gut health and sleep quality", "Sleep Science"),
  s("Why inflammation disrupts sleep", "Sleep Science"),
  s("How aging changes sleep architecture", "Sleep Science"),
  s("The link between serotonin and sleep", "Sleep Science"),
  s("How blood sugar spikes affect sleep quality", "Sleep Science"),
  s("Why alcohol destroys sleep quality (the science)", "Sleep Science"),
  s("How caffeine blocks adenosine receptors", "Sleep Science"),
  s("Why sleep is the brain's cleaning cycle", "Sleep Science"),
  s("Sleep spindles: what they are and why they matter", "Sleep Science"),
  s("How poor sleep raises cortisol the next day", "Sleep Science"),
  s("The two-process model of sleep regulation explained", "Sleep Science"),

  // Circadian Rhythm
  s("How light exposure sets your internal clock", "Circadian Rhythm"),
  s("The perfect morning routine to reset your circadian rhythm", "Circadian Rhythm"),
  s("Why eating late at night disrupts sleep", "Circadian Rhythm"),
  s("Social jet lag: why your weekend schedule ruins Monday", "Circadian Rhythm"),
  s("Blue light and its effect on melatonin production", "Circadian Rhythm"),
  s("The ideal time to take sleep supplements", "Circadian Rhythm"),
  s("Morning sunlight: the #1 circadian rhythm reset", "Circadian Rhythm"),
  s("How travel jet lag works (and how to beat it)", "Circadian Rhythm"),
  s("Why darkness matters as much as light for sleep", "Circadian Rhythm"),
  s("The relationship between meal timing and sleep quality", "Circadian Rhythm"),
  s("How exercise timing affects sleep quality", "Circadian Rhythm"),
  s("Temperature as a circadian signal for your body", "Circadian Rhythm"),
  s("Why teenagers naturally sleep later (delayed phase disorder)", "Circadian Rhythm"),
  s("Seasonal changes in sleep patterns explained", "Circadian Rhythm"),
  s("How shift work ages your body faster", "Circadian Rhythm"),

  // Sleep Hygiene
  s("The ideal bedroom temperature for deep sleep (18–19°C)", "Sleep Hygiene"),
  s("How to create a wind-down routine that actually works", "Sleep Hygiene"),
  s("Why screen time before bed ruins sleep quality", "Sleep Hygiene"),
  s("The 10-3-2-1-0 sleep rule explained", "Sleep Hygiene"),
  s("How consistent sleep timing transforms your sleep", "Sleep Hygiene"),
  s("Stimulus control: your bedroom should only be for sleep", "Sleep Hygiene"),
  s("White noise vs. silence: which helps you sleep better", "Sleep Hygiene"),
  s("How weighted blankets affect sleep quality", "Sleep Hygiene"),
  s("The power of a pre-sleep journaling routine", "Sleep Hygiene"),
  s("How to stop racing thoughts at bedtime", "Sleep Hygiene"),
  s("Sleep and hydration: finding the right balance", "Sleep Hygiene"),
  s("The optimal sleep schedule for adults", "Sleep Hygiene"),
  s("Napping: the rules for naps that don't ruin night sleep", "Sleep Hygiene"),
  s("How blackout curtains can transform your sleep", "Sleep Hygiene"),
  s("Why you should avoid clock-watching at night", "Sleep Hygiene"),
  s("Cold showers before bed: myth or sleep aid?", "Sleep Hygiene"),
  s("How bath timing improves sleep onset", "Sleep Hygiene"),
  s("The case against sleeping with your phone in the bedroom", "Sleep Hygiene"),
  s("Why you should stop checking your phone at night", "Sleep Hygiene"),
  s("Bedding materials that regulate temperature for better sleep", "Sleep Hygiene"),

  // Nutrition & Sleep
  s("Foods that naturally increase GABA levels", "Nutrition & Sleep"),
  s("The magnesium-rich foods you should eat more of", "Nutrition & Sleep"),
  s("Glycine-rich foods that improve sleep quality", "Nutrition & Sleep"),
  s("Why tart cherry juice boosts melatonin naturally", "Nutrition & Sleep"),
  s("How kiwi before bed improves sleep (the clinical study)", "Nutrition & Sleep"),
  s("Alcohol and sleep: why you wake up at 3am", "Nutrition & Sleep"),
  s("Caffeine half-life: when to stop drinking coffee", "Nutrition & Sleep"),
  s("Sugar and sleep: the blood sugar rollercoaster at night", "Nutrition & Sleep"),
  s("L-tryptophan foods that support serotonin production", "Nutrition & Sleep"),
  s("Why heavy meals before bed disrupt sleep", "Nutrition & Sleep"),
  s("Herbal teas that support better sleep quality", "Nutrition & Sleep"),
  s("How fasting affects sleep quality", "Nutrition & Sleep"),
  s("Omega-3 fatty acids and sleep quality research", "Nutrition & Sleep"),
  s("Vitamin D deficiency and poor sleep: the link", "Nutrition & Sleep"),
  s("The magnesium content of common foods (you're probably deficient)", "Nutrition & Sleep"),

  // Mental Health & Sleep
  s("How chronic stress destroys sleep architecture", "Mental Health & Sleep"),
  s("The anxiety-insomnia cycle (and how to break it)", "Mental Health & Sleep"),
  s("How sleep deprivation mimics the effects of anxiety", "Mental Health & Sleep"),
  s("Cognitive behavioral therapy for insomnia (CBT-I) explained", "Mental Health & Sleep"),
  s("Why poor sleep makes you emotionally reactive", "Mental Health & Sleep"),
  s("Sleep and depression: what comes first?", "Mental Health & Sleep"),
  s("How mindfulness meditation improves sleep", "Mental Health & Sleep"),
  s("Breathing techniques that activate the parasympathetic system", "Mental Health & Sleep"),
  s("The 4-7-8 breathing method for sleep onset", "Mental Health & Sleep"),
  s("Progressive muscle relaxation for better sleep", "Mental Health & Sleep"),
  s("How gratitude practice affects sleep quality", "Mental Health & Sleep"),
  s("The link between loneliness and insomnia", "Mental Health & Sleep"),
  s("How burnout affects sleep quality and recovery", "Mental Health & Sleep"),
  s("Why poor sleep makes you reach for junk food", "Mental Health & Sleep"),
  s("Sleep and creativity: how your brain solves problems overnight", "Mental Health & Sleep"),

  // Performance & Recovery
  s("How elite athletes prioritize sleep for performance", "Performance & Recovery"),
  s("Sleep and muscle recovery: the science behind it", "Performance & Recovery"),
  s("Growth hormone release during deep sleep", "Performance & Recovery"),
  s("How poor sleep reduces athletic performance by 20–30%", "Performance & Recovery"),
  s("Sleep and reaction time: the shocking statistics", "Performance & Recovery"),
  s("Why sleep is the best performance enhancer (Matthew Walker)", "Performance & Recovery"),
  s("Sleep and cognitive performance: what the research shows", "Performance & Recovery"),
  s("The memory consolidation that happens while you sleep", "Performance & Recovery"),
  s("How sleep deprivation impairs decision making", "Performance & Recovery"),
  s("Sleep debt: can you really catch up on weekends?", "Performance & Recovery"),
  s("How sleep deprivation affects testosterone levels", "Performance & Recovery"),
  s("Sleep and immune function: recovering faster with quality sleep", "Performance & Recovery"),
  s("How poor sleep slows metabolism", "Performance & Recovery"),
  s("The productivity cost of bad sleep (the numbers)", "Performance & Recovery"),
  s("Why Roger Federer and LeBron James sleep 10–12 hours a night", "Performance & Recovery"),

  // Lunia Ingredients
  s("Magnesium glycinate vs. magnesium citrate: what's the difference", "Lunia Ingredients"),
  s("Why the glycinate form of magnesium is best for sleep", "Lunia Ingredients"),
  s("L-theanine: from green tea leaf to sleep supplement", "Lunia Ingredients"),
  s("Apigenin: why chamomile tea makes you sleepy", "Lunia Ingredients"),
  s("The synergy between magnesium, L-theanine, and apigenin", "Lunia Ingredients"),
  s("Why 400mg magnesium is the evidence-based sleep dose", "Lunia Ingredients"),
  s("Apigenin and GABA-A receptors: the mechanism explained", "Lunia Ingredients"),
  s("Why Lunia contains no melatonin (and why that's better)", "Lunia Ingredients"),
  s("The case against relying on melatonin long-term", "Lunia Ingredients"),
  s("Non-habit forming sleep support: how it works", "Lunia Ingredients"),
  s("Third-party testing: why it matters for sleep supplements", "Lunia Ingredients"),
  s("cGMP certification: what it means for supplement quality", "Lunia Ingredients"),
  s("What to look for in a clean sleep supplement", "Lunia Ingredients"),
  s("How L-theanine dose affects relaxation without drowsiness", "Lunia Ingredients"),
  s("Lunia formula: every ingredient and why it's included", "Lunia Ingredients"),

  // Sleep Disorders
  s("Insomnia: the two types and how to treat each", "Sleep Disorders"),
  s("Sleep apnea: signs, risks, and solutions", "Sleep Disorders"),
  s("Restless legs syndrome and magnesium deficiency", "Sleep Disorders"),
  s("Why women are twice as likely to have insomnia", "Sleep Disorders"),
  s("Paradoxical insomnia: when you're sleeping but don't feel rested", "Sleep Disorders"),
  s("How to know if you have a sleep disorder", "Sleep Disorders"),
  s("The dangers of untreated sleep apnea", "Sleep Disorders"),
  s("Sleep paralysis: what it is and why it happens", "Sleep Disorders"),
  s("Delayed sleep phase disorder (DSPD) explained", "Sleep Disorders"),
  s("Hypersomnia: when you sleep too much but still feel tired", "Sleep Disorders"),

  // Lifestyle & Productivity
  s("The morning routines of high performers (sleep-first approach)", "Lifestyle & Productivity"),
  s("How bad sleep is silently costing you hours of productivity", "Lifestyle & Productivity"),
  s("Why CEOs and athletes are obsessed with sleep tracking", "Lifestyle & Productivity"),
  s("Sleep tracking: does it actually improve your sleep?", "Lifestyle & Productivity"),
  s("How good sleep transforms your skin overnight", "Lifestyle & Productivity"),
  s("The link between sleep and weight management", "Lifestyle & Productivity"),
  s("Sleep and longevity: what the research shows", "Lifestyle & Productivity"),
  s("Why Jeff Bezos protects his 8 hours of sleep", "Lifestyle & Productivity"),
  s("The sleep-first philosophy: building your day backward from bedtime", "Lifestyle & Productivity"),
  s("How sleep quality affects your relationships", "Lifestyle & Productivity"),
  s("Why Arianna Huffington had a wake-up call about sleep", "Lifestyle & Productivity"),
  s("The hidden cost of sleeping pills nobody talks about", "Lifestyle & Productivity"),
  s("Building a sleep-first lifestyle: where to start", "Lifestyle & Productivity"),
  s("How sleep deprivation affects your social life", "Lifestyle & Productivity"),
  s("Sleep and financial decision-making: why tired people make bad choices", "Lifestyle & Productivity"),
  s("What happens to your body after one week of great sleep", "Lifestyle & Productivity"),
  s("Sleep and parenting: how your sleep affects your kids", "Lifestyle & Productivity"),
  s("How to talk to your doctor about sleep problems", "Lifestyle & Productivity"),
  s("The 5 biggest sleep mistakes most people make", "Lifestyle & Productivity"),
  s("What a sleep scientist would never do before bed", "Lifestyle & Productivity"),

  // Longevity & Sleep Research
  s("Telomere length and sleep duration: the Whitehall II cohort study", "Longevity & Sleep Research"),
  s("How short sleep accelerates biological aging (epigenetic clocks)", "Longevity & Sleep Research"),
  s("Sleep and autophagy: how deep sleep triggers cellular cleanup", "Longevity & Sleep Research"),
  s("NAD+ decline, sirtuin activity, and sleep quality with age", "Longevity & Sleep Research"),
  s("The glymphatic system: how sleep washes toxins from your brain (Xie et al. 2013)", "Longevity & Sleep Research"),
  s("Sleep deprivation and amyloid-beta accumulation (Shokri-Kojori 2018)", "Longevity & Sleep Research"),
  s("Cardiovascular mortality and sleep duration: the U-shaped curve (Cappuccio 2010)", "Longevity & Sleep Research"),
  s("Why sleeping less than 6 hours doubles your heart attack risk", "Longevity & Sleep Research"),
  s("Sleep restriction and inflammatory aging markers (Irwin 2015)", "Longevity & Sleep Research"),
  s("How chronic sleep loss elevates C-reactive protein and IL-6", "Longevity & Sleep Research"),
  s("Blue Zone sleep patterns: what centenarians in Okinawa do differently", "Longevity & Sleep Research"),
  s("Sardinian longevity and afternoon napping traditions", "Longevity & Sleep Research"),
  s("Ikaria sleep habits: 9-hour nights and the longevity connection", "Longevity & Sleep Research"),
  s("Growth hormone pulsatility during slow-wave sleep and aging", "Longevity & Sleep Research"),
  s("How deep sleep decline after 30 accelerates aging", "Longevity & Sleep Research"),
  s("Sleep fragmentation and all-cause mortality risk (meta-analysis)", "Longevity & Sleep Research"),
  s("DNA repair during sleep: how your genome heals overnight", "Longevity & Sleep Research"),
  s("Oxidative stress accumulation from chronic sleep restriction", "Longevity & Sleep Research"),
  s("Sleep and insulin sensitivity: the diabetes-longevity connection", "Longevity & Sleep Research"),
  s("How one week of sleep restriction changes 711 genes (Moller-Levet 2013)", "Longevity & Sleep Research"),
  s("Shift work and lifespan reduction: the Nurses' Health Study findings", "Longevity & Sleep Research"),
  s("Sleep apnea and accelerated biological aging", "Longevity & Sleep Research"),
  s("Melatonin as an antioxidant: the longevity molecule you make while sleeping", "Longevity & Sleep Research"),
  s("How sleep quality predicts all-cause mortality better than duration", "Longevity & Sleep Research"),
  s("The mitochondrial theory of aging and sleep's role in energy repair", "Longevity & Sleep Research"),
  s("Chronic insomnia and 10-year mortality risk (Vgontzas 2010)", "Longevity & Sleep Research"),
  s("Why Matthew Walker calls sleep 'the single most effective thing you can do to reset brain and body health'", "Longevity & Sleep Research"),
  s("Sleep, mTOR, and the longevity signaling pathways", "Longevity & Sleep Research"),
  s("Caloric restriction, sleep, and lifespan extension in animal models", "Longevity & Sleep Research"),
  s("How sleep debt compounds: the hidden cost of 'just one less hour'", "Longevity & Sleep Research"),
  s("The bidirectional link between sleep and telomerase activity", "Longevity & Sleep Research"),
  s("Sleep and stem cell renewal: how rest powers regeneration", "Longevity & Sleep Research"),
  s("Brain age and sleep: MRI studies showing sleep deprivation ages the brain", "Longevity & Sleep Research"),
  s("Sleep duration and cognitive decline risk over 25 years (Sabia 2021)", "Longevity & Sleep Research"),
  s("How poor sleep in midlife predicts dementia risk decades later", "Longevity & Sleep Research"),
  s("The Harvard sleep and longevity study: 5 sleep habits that add years", "Longevity & Sleep Research"),
  s("Sleep consistency vs. duration: which matters more for longevity", "Longevity & Sleep Research"),
  s("Circadian disruption and cancer risk: the IARC classification", "Longevity & Sleep Research"),
  s("How night shift work affects chromosomal integrity", "Longevity & Sleep Research"),
  s("REM sleep loss and emotional aging: why sleep keeps you mentally young", "Longevity & Sleep Research"),
  s("Sleep-dependent memory consolidation and cognitive reserve in aging", "Longevity & Sleep Research"),
  s("The FOXO3 longevity gene and its regulation during sleep", "Longevity & Sleep Research"),
  s("Klotho protein, sleep quality, and anti-aging effects", "Longevity & Sleep Research"),
  s("How 8 hours of sleep reduces your biological age by years", "Longevity & Sleep Research"),
  s("Sleep and wound healing speed: the recovery-longevity link", "Longevity & Sleep Research"),
  s("Cortisol dysregulation from poor sleep and premature aging", "Longevity & Sleep Research"),
  s("The Oura Ring generation: what wearable data reveals about sleep and healthspan", "Longevity & Sleep Research"),
  s("Sleep regularity index: why consistent bedtimes beat total hours", "Longevity & Sleep Research"),
  s("Microbiome diversity, sleep quality, and longevity connections", "Longevity & Sleep Research"),
  s("How intermittent fasting combined with good sleep amplifies autophagy", "Longevity & Sleep Research"),
  s("Peter Attia on sleep as the foundation of longevity protocols", "Longevity & Sleep Research"),
  s("David Sinclair's information theory of aging and sleep's protective role", "Longevity & Sleep Research"),
  s("Rhonda Patrick on time-restricted eating and circadian sleep optimization", "Longevity & Sleep Research"),
  s("Andrew Huberman's non-sleep deep rest (NSDR) protocol for recovery", "Longevity & Sleep Research"),
  s("The Whitehall II study: 5-hour sleepers have 30% higher mortality", "Longevity & Sleep Research"),
  s("Sleep and thymic involution: immune aging tied to rest quality", "Longevity & Sleep Research"),
  s("How polyphenols and sleep synergize for anti-aging effects", "Longevity & Sleep Research"),
  s("Sleep architecture changes across the lifespan: what to expect at every decade", "Longevity & Sleep Research"),
  s("Centenarian sleep studies: 7-8 hours with high sleep efficiency", "Longevity & Sleep Research"),
  s("The dose-response relationship between sleep and lifespan (systematic review)", "Longevity & Sleep Research"),

  // Additional Sleep Science (research deep-dives)
  s("How orexin neurons control the sleep-wake switch", "Sleep Science"),
  s("Adenosine A1 vs A2A receptors: two pathways to sleepiness", "Sleep Science"),
  s("The suprachiasmatic nucleus: your brain's master clock explained", "Sleep Science"),
  s("Thalamocortical oscillations and the generation of sleep spindles", "Sleep Science"),
  s("How the locus coeruleus goes silent during REM sleep", "Sleep Science"),
  s("Pontine brainstem circuits that trigger REM atonia", "Sleep Science"),
  s("The flip-flop switch model of sleep-wake regulation (Saper 2005)", "Sleep Science"),
  s("Hypocretin deficiency: the neuroscience behind narcolepsy", "Sleep Science"),
  s("How prostaglandin D2 accumulates to build sleep pressure", "Sleep Science"),
  s("The default mode network during NREM sleep: brain connectivity insights", "Sleep Science"),
  s("Sharp-wave ripples in the hippocampus: memory replay during sleep", "Sleep Science"),
  s("How sleep deprivation impairs prefrontal cortex function (Yoo 2007)", "Sleep Science"),
  s("The role of astrocytes in regulating sleep homeostasis", "Sleep Science"),
  s("Optogenetics studies revealing causal sleep circuits (Adamantidis 2007)", "Sleep Science"),
  s("How TNF-alpha and cytokines regulate local sleep in the cortex", "Sleep Science"),

  // Additional Nutrition & Sleep (research papers)
  s("The DASH diet and sleep quality: systematic review findings", "Nutrition & Sleep"),
  s("Mediterranean diet adherence and sleep quality in older adults", "Nutrition & Sleep"),
  s("Gut-brain axis: how probiotic strains affect sleep architecture", "Nutrition & Sleep"),
  s("Tryptophan depletion studies: what happens when you remove the sleep amino acid", "Nutrition & Sleep"),
  s("Magnesium supplementation and insomnia: the Abbasi 2012 clinical trial", "Nutrition & Sleep"),
  s("Zinc and sleep: the overlooked mineral for sleep initiation", "Nutrition & Sleep"),
  s("How glycine supplementation improves next-day performance (Bannai 2012)", "Nutrition & Sleep"),
  s("Iron deficiency, restless legs, and disrupted sleep architecture", "Nutrition & Sleep"),
  s("Ashwagandha (KSM-66) and sleep quality: randomized controlled trial results", "Nutrition & Sleep"),
  s("Phosphatidylserine and cortisol blunting for better sleep onset", "Nutrition & Sleep"),

  // Additional Performance & Recovery (research papers)
  s("Sleep extension in collegiate basketball players: the Mah 2011 Stanford study", "Performance & Recovery"),
  s("How 10 hours of sleep improved sprint times and free-throw accuracy", "Performance & Recovery"),
  s("Sleep and injury risk in adolescent athletes (Milewski 2014)", "Performance & Recovery"),
  s("The military sleep research: cognitive degradation after 24 hours awake", "Performance & Recovery"),
  s("Microsleep episodes: the hidden danger of sleep-deprived driving", "Performance & Recovery"),
  s("How sleep boosts motor skill learning (Walker 2002)", "Performance & Recovery"),
  s("Heat shock proteins and deep sleep: the recovery mechanism athletes need", "Performance & Recovery"),
  s("Erythropoietin release during sleep: blood cell recovery overnight", "Performance & Recovery"),
  s("Sleep and pain threshold: why sleep-deprived people feel more pain", "Performance & Recovery"),
  s("The 2-week sleep restriction study: subjective adaptation vs. objective decline", "Performance & Recovery"),

  // Did You Know — frozen-template format (100 entries)
  s("Sleeping less than 6 hours raises cortisol the next day", "Did You Know"),
  s("Deep sleep clears beta-amyloid from the brain", "Did You Know"),
  s("Women lose deep sleep faster than men with age", "Did You Know"),
  s("REM sleep peaks in the last third of the night", "Did You Know"),
  s("Body temperature must drop 1°F to fall asleep", "Did You Know"),
  s("Blue light delays melatonin release by up to 90 minutes", "Did You Know"),
  s("Magnesium glycinate is absorbed better than oxide", "Did You Know"),
  s("Caffeine has a 6-hour half-life in most adults", "Did You Know"),
  s("Alcohol cuts REM sleep by up to 40 percent", "Did You Know"),
  s("Perimenopause reduces deep sleep by ~30 minutes per night", "Did You Know"),
  s("Sleep debt cannot be fully repaid on weekends", "Did You Know"),
  s("Cortisol naturally peaks within 30 minutes of waking", "Did You Know"),
  s("Light exposure within 1 hour of waking anchors your circadian rhythm", "Did You Know"),
  s("Late dinners delay melatonin and shorten deep sleep", "Did You Know"),
  s("Resting heart rate drops 10-20 BPM during deep sleep", "Did You Know"),
  s("Heart rate variability predicts sleep quality better than duration", "Did You Know"),
  s("Estrogen affects serotonin and sleep architecture", "Did You Know"),
  s("Progesterone has natural sedative effects on the brain", "Did You Know"),
  s("Iron deficiency causes restless legs and disrupted sleep", "Did You Know"),
  s("L-theanine in tea creates calm without sedation", "Did You Know"),
  s("Glycine before bed lowers core body temperature", "Did You Know"),
  s("Apigenin in chamomile binds to GABA receptors", "Did You Know"),
  s("Lavender essential oil reduces sleep onset by ~8 minutes", "Did You Know"),
  s("Mouth breathing during sleep raises blood pressure", "Did You Know"),
  s("Sleep position affects glymphatic brain cleaning", "Did You Know"),
  s("Cool bedrooms (65-68°F) deepen slow-wave sleep", "Did You Know"),
  s("Weighted blankets raise melatonin by ~30 percent", "Did You Know"),
  s("Mouth taping can reduce snoring in healthy adults", "Did You Know"),
  s("Nasal breathing increases nitric oxide and oxygenation", "Did You Know"),
  s("Sleep deprivation reduces facial attractiveness in studies", "Did You Know"),
  s("One night of poor sleep reduces insulin sensitivity", "Did You Know"),
  s("Growth hormone releases mostly in the first 90 minutes of sleep", "Did You Know"),
  s("Sleep duration affects how vaccines work", "Did You Know"),
  s("Women need ~20 minutes more sleep than men on average", "Did You Know"),
  s("Sleep apnea is underdiagnosed in women by up to 90 percent", "Did You Know"),
  s("Menstrual cycle changes core body temperature and sleep", "Did You Know"),
  s("Pregnancy increases REM sleep in the first trimester", "Did You Know"),
  s("Postpartum sleep fragmentation lasts ~6 months on average", "Did You Know"),
  s("The brain shrinks ~60 percent in volume during deep sleep cleaning", "Did You Know"),
  s("Glymphatic flow increases 60 percent during sleep", "Did You Know"),
  s("Shift work raises breast cancer risk by ~30 percent", "Did You Know"),
  s("Social jet lag is more harmful than weekend travel", "Did You Know"),
  s("Eating within 2 hours of bed raises nighttime glucose", "Did You Know"),
  s("Alcohol metabolizes faster but disrupts the second half of sleep", "Did You Know"),
  s("Cannabis reduces REM sleep across regular users", "Did You Know"),
  s("Magnesium L-threonate crosses the blood-brain barrier", "Did You Know"),
  s("Zinc plays a role in melatonin production", "Did You Know"),
  s("Vitamin D deficiency is linked to insomnia", "Did You Know"),
  s("Omega-3s improve sleep quality in adolescents", "Did You Know"),
  s("Tart cherry juice raises natural melatonin", "Did You Know"),
  s("Kiwi fruit before bed improves sleep onset and duration", "Did You Know"),
  s("Honey at bedtime stabilizes overnight blood sugar", "Did You Know"),
  s("Resistance training in the morning improves sleep that night", "Did You Know"),
  s("Late-evening exercise can delay sleep onset", "Did You Know"),
  s("Sauna use 1-2 hours before bed deepens sleep", "Did You Know"),
  s("Cold plunges in the morning improve sleep that night", "Did You Know"),
  s("Hot baths 90 minutes before bed help you fall asleep faster", "Did You Know"),
  s("White noise reduces nighttime awakenings", "Did You Know"),
  s("Pink noise has been shown to enhance deep sleep memory consolidation", "Did You Know"),
  s("Reading on paper before bed reduces sleep latency", "Did You Know"),
  s("Worry-journaling for 5 minutes cuts sleep onset time", "Did You Know"),
  s("Box breathing lowers heart rate within 4 minutes", "Did You Know"),
  s("Yoga nidra produces measurable theta brain waves", "Did You Know"),
  s("Sleep spindles correlate with memory consolidation", "Did You Know"),
  s("Dream recall is highest after waking from REM sleep", "Did You Know"),
  s("Sleep timing matters more than duration for some hormones", "Did You Know"),
  s("Going to bed at the same time daily lowers heart disease risk", "Did You Know"),
  s("Sleep regularity predicts mortality better than sleep duration", "Did You Know"),
  s("Naps over 30 minutes can interfere with nighttime sleep", "Did You Know"),
  s("A 20-minute nap restores alertness without grogginess", "Did You Know"),
  s("Sleep inertia can last up to 2 hours after waking", "Did You Know"),
  s("Sunlight on the eyes within 30 minutes of waking sets your clock", "Did You Know"),
  s("Even cloudy daylight is 10x brighter than indoor light", "Did You Know"),
  s("Indoor light is too dim to anchor circadian rhythm", "Did You Know"),
  s("Evening light shifts your sleep phase later", "Did You Know"),
  s("Red-shifted light has minimal effect on melatonin", "Did You Know"),
  s("Sleep loss reduces empathy and emotional regulation", "Did You Know"),
  s("One night of sleep loss raises amygdala reactivity by 60 percent", "Did You Know"),
  s("Sleep-deprived people misread neutral faces as threatening", "Did You Know"),
  s("Chronic sleep loss raises Alzheimer's risk markers", "Did You Know"),
  s("Sleep loss makes the brain crave high-calorie food", "Did You Know"),
  s("Ghrelin rises and leptin falls after a poor night of sleep", "Did You Know"),
  s("Sleep deprivation reduces athletic performance by ~20 percent", "Did You Know"),
  s("Reaction time after 17 hours awake equals being legally drunk", "Did You Know"),
  s("Microsleeps occur even when you feel awake", "Did You Know"),
  s("Sleep loss reduces testosterone in men under 30", "Did You Know"),
  s("Sleep loss disrupts ovulation hormones in women", "Did You Know"),
  s("Cortisol awakening response is blunted after poor sleep", "Did You Know"),
  s("Inflammation markers rise after a single night of poor sleep", "Did You Know"),
  s("Sleep affects gut microbiome diversity", "Did You Know"),
  s("Vagal tone improves with consistent sleep timing", "Did You Know"),
  s("Sleep helps consolidate procedural and motor learning", "Did You Know"),
  s("New skills improve overnight without practice", "Did You Know"),
  s("Sleep-dependent memory consolidation peaks in slow-wave sleep", "Did You Know"),
  s("REM sleep helps process emotional memories", "Did You Know"),
  s("Sleeping after learning improves test performance", "Did You Know"),
  s("Insomnia is twice as common in women as in men", "Did You Know"),
  s("Sleep architecture changes every decade after 30", "Did You Know"),
  s("Older adults need the same sleep but get less of it", "Did You Know"),
  s("Sleep efficiency drops ~10 percent per decade after age 30", "Did You Know"),
  s("Aging shifts sleep timing earlier by ~1 hour per decade after 50", "Did You Know"),
  s("The brain produces less melatonin with age", "Did You Know"),
  s("Sleep is the strongest non-negotiable lever for longevity", "Did You Know"),
];

export const DEFAULT_SUBJECTS: Subject[] = [...SLEEP_TOPICS, ...DEFAULT_RESEARCHERS];
