"use client";
import CopyButton from "@/components/email-review/CopyButton";
import MarkdownRenderer from "@/components/email-review/MarkdownRenderer";
import type { AdditionalEmail } from "@/lib/types";

type Props = {
  emails: AdditionalEmail[];
};

function fullEmailMarkdown(e: AdditionalEmail): string {
  const alts = e.subjectAlts.length ? `\n\n**Subject alternatives:**\n\n${e.subjectAlts.map((a) => `- ${a}`).join("\n")}` : "";
  return `## ${e.role}\n\n_Position E${e.position} · send at +${e.sendDelayHours}h · ${e.senderName} <${e.senderEmail}>_\n\n**Subject:** ${e.subjectA}\n\n**Preview:** ${e.previewText}${alts}\n\n---\n\n${e.bodyMarkdown}\n\n_Rationale: ${e.rationale}_`;
}

export default function AdditionalEmailsDeck({ emails }: Props) {
  if (!emails.length) return null;

  return (
    <section style={{ display: "flex", flexDirection: "column", gap: 14 }}>
      <header style={{ display: "flex", alignItems: "center", justifyContent: "space-between", gap: 12, flexWrap: "wrap" }}>
        <div>
          <h2 style={{ margin: 0, fontFamily: "Arial, sans-serif", fontSize: 18, fontWeight: 700, color: "#102635" }}>
            New emails to add to this flow
          </h2>
          <div style={{ fontSize: 12, color: "var(--muted)", marginTop: 2 }}>
            Generated by Opus 4.7 to bring this flow up to canon. Voice-matched to the existing rewrites. Inter typography assumed.
          </div>
        </div>
        <CopyButton
          text={emails.map(fullEmailMarkdown).join("\n\n---\n\n")}
          label="Copy all"
          size="md"
        />
      </header>

      <div style={{ display: "flex", flexDirection: "column", gap: 14 }}>
        {emails.map((e) => (
          <article
            key={e.id}
            style={{
              background: "var(--surface)",
              border: "1px solid var(--border)",
              borderLeft: "4px solid #FFD800",
              borderRadius: 12,
              overflow: "hidden",
            }}
          >
            <header style={{ background: "#F5F2EC", padding: "12px 18px", display: "flex", alignItems: "center", justifyContent: "space-between", gap: 8, flexWrap: "wrap" }}>
              <div style={{ display: "flex", alignItems: "center", gap: 10, flexWrap: "wrap" }}>
                <span style={{ padding: "3px 9px", background: "#102635", color: "#fff", fontSize: 10, fontWeight: 700, letterSpacing: "0.06em", borderRadius: 3, textTransform: "uppercase" }}>
                  E{e.position}
                </span>
                <span style={{ fontFamily: "Arial, sans-serif", fontSize: 15, fontWeight: 700, color: "#102635" }}>{e.role}</span>
                <span style={{ fontFamily: "Arial, sans-serif", fontSize: 11, color: "#5b5340", letterSpacing: "0.04em", textTransform: "uppercase", fontWeight: 600 }}>
                  +{e.sendDelayHours}h
                </span>
              </div>
              <CopyButton text={fullEmailMarkdown(e)} label="Copy email" />
            </header>

            <div style={{ padding: "16px 22px 18px", display: "flex", flexDirection: "column", gap: 14 }}>
              <div style={{ display: "grid", gridTemplateColumns: "max-content 1fr", gap: "8px 14px", fontFamily: "Arial, sans-serif", fontSize: 13 }}>
                <Label>Subject</Label>
                <div style={{ color: "#1A1A1A", fontWeight: 700 }}>{e.subjectA}</div>
                {e.subjectAlts.length > 0 && (
                  <>
                    <Label>A/B alts</Label>
                    <ul style={{ margin: 0, padding: 0, listStyle: "none", display: "flex", flexDirection: "column", gap: 4 }}>
                      {e.subjectAlts.map((alt, i) => (
                        <li key={i} style={{ display: "flex", alignItems: "flex-start", gap: 6, color: "#1A1A1A" }}>
                          <span style={{ flexShrink: 0, fontSize: 10, fontWeight: 700, color: "#5b5340", letterSpacing: "0.04em", paddingTop: 2 }}>ALT {i + 1}</span>
                          <span style={{ flex: 1 }}>{alt}</span>
                        </li>
                      ))}
                    </ul>
                  </>
                )}
                <Label>Preview</Label>
                <div style={{ color: "#1A1A1A" }}>{e.previewText}</div>
                <Label>Sender</Label>
                <div style={{ color: "#1A1A1A" }}>
                  {e.senderName} <span style={{ color: "var(--subtle)" }}>&lt;{e.senderEmail}&gt;</span>
                </div>
              </div>

              <div style={{ borderTop: "1px dashed #d6cfbe", paddingTop: 12 }}>
                <MarkdownRenderer>{e.bodyMarkdown}</MarkdownRenderer>
              </div>

              {e.rationale && (
                <div style={{ marginTop: 4, padding: "8px 12px", background: "var(--surface-r)", border: "1px solid var(--border)", borderRadius: 6, fontSize: 12, color: "var(--muted)", fontStyle: "italic", lineHeight: 1.5 }}>
                  <strong style={{ color: "var(--text)", fontStyle: "normal", marginRight: 6 }}>Why:</strong>
                  {e.rationale}
                </div>
              )}
            </div>
          </article>
        ))}
      </div>
    </section>
  );
}

function Label({ children }: { children: React.ReactNode }) {
  return (
    <span style={{ fontSize: 10, fontWeight: 700, letterSpacing: "0.08em", textTransform: "uppercase", color: "var(--subtle)", fontFamily: "Arial, sans-serif", paddingTop: 3 }}>
      {children}
    </span>
  );
}
